title: Aleksandar Karastoyanov's CV
description: 
url: https://github.com/karastoyanov/karastoyanov-cv 
baseurl: ''
theme_skin: blue


sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml

